app/client/forms/mode_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError

class CreateModeForm(FlaskForm):
    crtmd_name_input = StringField("Name", validators=[DataRequired(), Length(min=1, max=50)])

    crtmd_submit_input = SubmitField("Create")

class EditModeForm(FlaskForm):
    edtmd_id_input = StringField("Identifier", validators=[DataRequired()])
    edtmd_name_input = StringField("Name", validators=[DataRequired(), Length(min=1, max=50)])

    edtmd_submit_input = SubmitField("Edit")

class DeleteModeForm(FlaskForm):
    deltmd_id_input = StringField("Identifier", validators=[DataRequired()])
    deltmd_name_input = StringField("Name", validators=[DataRequired(), Length(min=1, max=50)])

    deltmd_submit_input = SubmitField("Delete")

app/client/forms/nature_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError

class CreateNatureForm(FlaskForm):
    crtnt_name_input = StringField("Name", validators=[DataRequired(), Length(min=1, max=50)])

    crtnt_submit_input = SubmitField("Create")

class EditNatureForm(FlaskForm):
    edtnt_id_input = StringField("Identifier", validators=[DataRequired()])
    edtnt_name_input = StringField("Name", validators=[DataRequired(), Length(min=1, max=50)])

    edtnt_submit_input = SubmitField("Edit")

class DeleteNatureForm(FlaskForm):
    deltnt_id_input = StringField("Identifier", validators=[DataRequired()])
    deltnt_name_input = StringField("Name", validators=[DataRequired(), Length(min=1, max=50)])

    deltnt_submit_input = SubmitField("Delete")

app/client/forms/office_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError

class CreateOfficeForm(FlaskForm):
    crtof_name_input = StringField("Name", validators=[DataRequired(), Length(min=1, max=50)])

    crtof_submit_input = SubmitField("Create")

class EditOfficeForm(FlaskForm):
    edtof_id_input = StringField("Identifier", validators=[DataRequired()])
    edtof_name_input = StringField("Name", validators=[DataRequired(), Length(min=1, max=50)])

    edtof_submit_input = SubmitField("Edit")

class DeleteOfficeForm(FlaskForm):
    deltof_id_input = StringField("Identifier", validators=[DataRequired()])
    deltof_name_input = StringField("Name", validators=[DataRequired(), Length(min=1, max=50)])

    deltof_submit_input = SubmitField("Delete")

app/client/forms/technician_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError

class CreateTechnicianForm(FlaskForm):
    crttc_name_input = StringField("Name", validators=[DataRequired(), Length(min=1, max=50)])

    crttc_submit_input = SubmitField("Create")

class EditTechnicianForm(FlaskForm):
    edttc_id_input = StringField("Identifier", validators=[DataRequired()])
    edttc_name_input = StringField("Name", validators=[DataRequired(), Length(min=1, max=50)])

    edttc_submit_input = SubmitField("Edit")

class DeleteTechnicianForm(FlaskForm):
    delttc_id_input = StringField("Identifier", validators=[DataRequired()])
    delttc_name_input = StringField("Name", validators=[DataRequired(), Length(min=1, max=50)])

    delttc_submit_input = SubmitField("Delete")

app/client/__init__.py
from flask import Blueprint

def create_client_bp():
    client_blueprint = Blueprint("client", __name__, template_folder="templates", static_url_path="static")
    
    return client_blueprint

app/client/controllers/__init__.py
from .dashboard_controller import *
from .requests_controller import *

app/client/controllers/dashboard_controller.py
import datetime
from flask import render_template, url_for, flash, redirect, request
from ... import client_bp
from ..services.request_service import RequestService
from ..services.technician_service import TechnicianService

@client_bp.route("/", methods=["GET", "POST"])
def dashboard():
    return render_template("dashboard.html",
        page_title = "Dashboard",
        current_date = "{}".format(datetime.datetime.utcnow().strftime("%B %d, %Y")),
        request_count = 2,
        technician_count = 2
    )

app/client/controllers/requests_controller.py
import itertools
from flask import render_template, url_for, flash, redirect, request, abort
from ... import client_bp
from ..forms.request_form import CreateRequestForm
from ..forms.office_form import *
from ..forms.mode_form import *
from ..forms.nature_form import *
from ..forms.technician_form import *
from ..services.request_service import RequestService
from ..services.office_service import OfficeService
from ..services.mode_service import ModeService
from ..services.nature_service import NatureService
from ..services.technician_service import TechnicianService
from ..utils._error_handlers import * 

@client_bp.route("/requests", methods=["GET", "POST"])
def requests():
    createRequestForm = CreateRequestForm()
    createOfficeForm = CreateOfficeForm()
    createModeForm = CreateModeForm()
    createNatureForm = CreateNatureForm()
    createTechnicianForm = CreateTechnicianForm()

    editOfficeForm = EditOfficeForm()
    editModeForm = EditModeForm()
    editNatureForm = EditNatureForm()
    editTechnicianForm = EditTechnicianForm()

    deleteOfficeForm = DeleteOfficeForm()
    deleteModeForm = DeleteModeForm()
    deleteNatureForm = DeleteNatureForm()
    deleteTechnicianForm = DeleteTechnicianForm()

    if request.method == "POST":
        if createRequestForm.crtrq_no_input.data:
            if createRequestForm.validate_on_submit():
                post_request_resp = RequestService.post(request)

                if not isinstance(post_request_resp, int):
                    flash("Request added successfully.", "success")

                    return redirect(url_for("client.requests"))

                abort(post_request_resp)

        if createOfficeForm.crtof_name_input.data:
            if createOfficeForm.validate_on_submit():
                post_office_resp = OfficeService.post(request)

                if not isinstance(post_office_resp, int):
                    flash("Office added successfully.", "success")

                    return redirect(url_for("client.requests"))

                abort(post_office_resp)

        if createModeForm.crtmd_name_input.data:
            if createModeForm.validate_on_submit():
                post_mode_resp = ModeService.post(request)

                if not isinstance(post_mode_resp, int):
                    flash("Mode added successfully.", "success")

                    return redirect(url_for("client.requests"))

                abort(post_mode_resp)

        if createNatureForm.crtnt_name_input.data:
            if createNatureForm.validate_on_submit():
                post_nature_resp = NatureService.post(request)

                if not isinstance(post_nature_resp, int):
                    flash("Nature added successfully.", "success")

                    return redirect(url_for("client.requests"))

                abort(post_nature_resp)

        if createTechnicianForm.crttc_name_input.data:
            if createTechnicianForm.validate_on_submit():
                post_technician_resp = TechnicianService.post(request)

                if not isinstance(post_technician_resp, int):
                    flash("Technician added successfully.", "success")

                    return redirect(url_for("client.requests"))

                abort(post_technician_resp)

        if editOfficeForm.edtof_id_input.data:
            if editOfficeForm.validate_on_submit():
                edit_office_resp = OfficeService.edit(request)

                if edit_office_resp == 200:
                    flash("Office edited successfully.", "success")

                    return redirect(url_for("client.requests"))

                abort(edit_office_resp)

        if editModeForm.edtmd_id_input.data:
            if editModeForm.validate_on_submit():
                edit_mode_resp = ModeService.edit(request)

                if edit_mode_resp == 200:
                    flash("Mode edited successfully.", "success")

                    return redirect(url_for("client.requests"))

                abort(edit_mode_resp)
        
        if editNatureForm.edtnt_id_input.data:
            if editNatureForm.validate_on_submit():
                edit_nature_resp = NatureService.edit(request)

                if edit_nature_resp == 200:
                    flash("Nature edited successfully.", "success")

                    return redirect(url_for("client.requests"))

                abort(edit_nature_resp)

        if editTechnicianForm.edttc_id_input.data:
            if editTechnicianForm.validate_on_submit():
                edit_technician_resp = TechnicianService.edit(request)

                if edit_technician_resp == 200:
                    flash("Technician edited successfully.", "success")

                    return redirect(url_for("client.requests"))

                abort(edit_technician_resp)

        if deleteOfficeForm.deltof_id_input.data:
            if deleteOfficeForm.validate_on_submit():
                delete_office_resp = OfficeService.delete(request)

                if delete_office_resp == 200:
                    flash("Office deleted successfully.", "success")

                    return redirect(url_for("client.requests"))

                abort(delete_office_resp)

        if deleteModeForm.deltmd_id_input.data:
            if deleteModeForm.validate_on_submit():
                delete_mode_resp = ModeService.delete(request)

                if delete_mode_resp == 200:
                    flash("Mode deleted successfully.", "success")

                    return redirect(url_for("client.requests"))

                abort(delete_mode_resp)
        
        if deleteNatureForm.deltnt_id_input.data:
            if deleteNatureForm.validate_on_submit():
                delete_nature_resp = NatureService.delete(request)

                if delete_nature_resp == 200:
                    flash("Nature deleted successfully.", "success")

                    return redirect(url_for("client.requests"))

                abort(delete_nature_resp)

        if deleteTechnicianForm.delttc_id_input.data:
            if deleteTechnicianForm.validate_on_submit():
                delete_technician_resp = TechnicianService.delete(request)

                if delete_technician_resp == 200:
                    flash("Technician deleted successfully.", "success")

                    return redirect(url_for("client.requests"))

                abort(delete_technician_resp)

    return render_template("requests.html",
        page_title="Requests",
        createRequestForm = createRequestForm,
        createOfficeForm = createOfficeForm,
        createModeForm = createModeForm,
        createNatureForm = createNatureForm,
        createTechnicianForm = createTechnicianForm,
        editOfficeForm = editOfficeForm,
        editModeForm = editModeForm,
        editNatureForm = editNatureForm,
        editTechnicianForm = editTechnicianForm,
        deleteOfficeForm = deleteOfficeForm,
        deleteModeForm = deleteModeForm,
        deleteNatureForm = deleteNatureForm,
        deleteTechnicianForm = deleteTechnicianForm
    )

app/server/controllers/request_controller.py
import time
from flask import request
from flask_restx import Resource
from ..services.request_service import RequestService
from ..utils._dtos import RequestDto

api = RequestDto.api
_request = RequestDto.request

@api.route("/")
class RequestList(Resource):
    @api.marshal_list_with(_request, envelope="requests")
    def get(self):
        pagination_no = request.args.get("pagination_no", 1, int)

        get_requests_resp = RequestService.get_all(pagination_no)

        if not isinstance(get_requests_resp, int):
            return get_requests_resp

        api.abort(get_requests_resp)

    @api.expect(_request, validate=True)
    def post(self):
        post_request_resp = RequestService.post(request.json)

        return post_request_resp if not isinstance(post_request_resp, int) else api.abort(post_request_resp)

@api.route("/year/<year>")
@api.param("year", "The Year specifier")
class RequestListByYear(Resource):
    @api.marshal_list_with(_request, envelope="requests")
    def get(self, year):
        pagination_no = request.args.get("pagination_no", 1, int)

        get_requests_resp = RequestService.get_by_year(year, pagination_no)

        if not isinstance(get_requests_resp, int):
            return get_requests_resp

        api.abort(get_requests_resp)

@api.route("/year/<year>/month/<month>")
@api.param("year", "The Request date year")
@api.param("month", "The Request date month")
class RequestListByYearAndMonth(Resource):
    @api.marshal_list_with(_request, envelope="requests")
    def get(self, year, month):
        pagination_no = request.args.get("pagination_no", 1, int)

        get_requests_resp = RequestService.get_by_year_and_month(year, month, pagination_no)

        if not isinstance(get_requests_resp, int):
            return get_requests_resp

        api.abort(get_requests_resp)

@api.route("/year/<year>/month/<month>/result/<result>")
@api.param("year", "The Request date year")
@api.param("month", "The Request date month")
@api.param("result", "The Request result")
class RequestListByYearAndMonthAndResult(Resource):
    @api.marshal_list_with(_request, envelope="requests")
    def get(self, year, month, result):
        pagination_no = request.args.get("pagination_no", 1, int)

        get_requests_resp = RequestService.get_by_year_and_month_and_result(year, month, result, pagination_no)

        if not isinstance(get_requests_resp, int):
            return get_requests_resp

        api.abort(get_requests_resp)

@api.route("/office/<office_id>")
@api.param("office_id", "The Office identifier")
class RequestListByOffice(Resource):
    @api.marshal_list_with(_request, envelope="requests")
    def get(self, office_id):
        pagination_no = request.args.get("pagination_no", 1, int)

        get_requests_resp = RequestService.get_by_office(office_id, pagination_no)

        if not isinstance(get_requests_resp, int):
            return get_requests_resp

        api.abort(get_requests_resp)

@api.route("/mode/<mode_id>")
@api.param("mode_id", "The Mode identifier")
class RequestListByMode(Resource):
    @api.marshal_list_with(_request, envelope="requests")
    def get(self, mode_id):
        pagination_no = request.args.get("pagination_no", 1, int)

        get_requests_resp = RequestService.get_by_mode(mode_id, pagination_no)
    
        if not isinstance(get_requests_resp, int):
            return get_requests_resp

        api.abort(get_requests_resp)

@api.route("/nature/<nature_id>")
@api.param("nature_id", "The Nature identifier")
class RequestListByNature(Resource):
    @api.marshal_list_with(_request, envelope="requests")
    def get(self, nature_id):
        pagination_no = request.args.get("pagination_no", 1, int)

        get_requests_resp = RequestService.get_by_nature(nature_id, pagination_no)

        if not isinstance(get_requests_resp, int):
            return get_requests_resp

        api.abort(get_requests_resp)

@api.route("/technician/<technician_id>")
@api.param("technician_id", "The Technician identifier")
class RequestListByTechnician(Resource):
    @api.marshal_list_with(_request, envelope="requests")
    def get(self, technician_id):
        pagination_no = request.args.get("pagination_no", 1, int)

        get_requests_resp = RequestService.get_by_technician(technician_id, pagination_no)

        if not isinstance(get_requests_resp, int):
            return get_requests_resp

        api.abort(get_requests_resp)

@api.route("/result/<result>")
@api.param("result", "The Request result")
class RequestListByResult(Resource):
    @api.marshal_list_with(_request, envelope="requests")
    def get(self, result):
        pagination_no = request.args.get("pagination_no", 1, int)

        get_requests_resp = RequestService.get_by_result(result, pagination_no)

        if not isinstance(get_requests_resp, int):
            return get_requests_resp

        api.abort(get_requests_resp)

@api.route("/rating/<rating>")
@api.param("rating", "The Request rating")
class RequestListByRating(Resource):
    @api.marshal_list_with(_request, envelope="requests")
    def get(self, rating):
        pagination_no = request.args.get("pagination_no", 1, int)

        get_requests_resp = RequestService.get_by_rating(rating, pagination_no)

        if not isinstance(get_requests_resp, int):
            return get_requests_resp

        api.abort(get_requests_resp)

@api.route("/detail/<detail>")
@api.param("detail", "The Request detail")
class RequestListByDetail(Resource):
    @api.marshal_list_with(_request, envelope="requests")
    def get(self, detail):
        pagination_no = request.args.get("pagination_no", 1, int)

        get_requests_resp = RequestService.get_by_detail(detail, pagination_no)

        if not isinstance(get_requests_resp, int):
            return get_requests_resp

        api.abort(get_requests_resp)

@api.route("/no/<no>/year/<year>")
@api.param("no", "The Request number")
@api.param("year", "The Request detail")
class RequestByNoAndYear(Resource):
    @api.marshal_with(_request)
    def get(self, no, year):
        pagination_no = request.args.get("pagination_no", 1, int)

        get_request = RequestService.get_by_no_and_year(no, year, pagination_no)

        if not isinstance(get_request, int):
            return get_request

        api.abort(get_request)

app/client/templates/components.html
{% macro sidebar(page_title) %}
    <div class="position-fixed d-flex flex-column justify-content-start align-items-center p-0">
        <div class="card p-5 border box-shadow vh-100 white">
            <div class="d-flex flex-column align-items-center">
                <img src="{{ url_for('static', filename='assets/ictc-name.svg') }}">
            </div>
            <div class="mt-5 d-flex flex-column">
                <a href="{{ url_for('client.dashboard') }}" class="text-{%if page_title == 'Dashboard'%}primary{%else%}secondary{%endif%} font-weight-bold d-flex flex-row align-items-center" role="button">
                    <span class="badge badge-{%if page_title == 'Dashboard'%}primary{%else%}secondary{%endif%}"><img src="{{ url_for('static', filename='assets/dashboard.svg') }}" style="width:15px;height:15px;"></span>&nbsp;&nbsp;Dashboard
                </a>
                <a href="{{ url_for('client.requests') }}" class="text-{%if page_title == 'Requests'%}primary{%else%}secondary{%endif%} font-weight-bold d-flex flex-row align-items-center mt-3" role="button">
                    <span class="badge badge-{%if page_title == 'Requests'%}primary{%else%}secondary{%endif%}"><img src="{{ url_for('static', filename='assets/request-light.svg') }}" style="width:15px;height:15px;"></span>&nbsp;&nbsp;Requests
                </a>
            </div>
        </div>
    </div>
{% endmacro %}

app/client/templates/dashboard.html
{% extends "layout.html" %}

{% block content %}
    <div class="db-tb container-fluid rounded position-fixed box-shadow d-flex justify-content-between px-0">
        <span class="p-3 font-weight-bold">
            Dashboard
        </span>
    </div>
    <div class="db-tc-dvd"></div>
    <div class="db-cc-fi card position-relative bg-light box-shadow d-flex flex-row justify-content-between align-items-center white">
        <div class="container-fluid my-2 d-flex flex-column align-items-center">
            <div class="card container-fluid p-0 bg-dark text-white">
                <div class="card-img" style="background-image: url('{{ url_for('static', filename='images/sample.jpg') }}');"></div>
                <div class="card-img-overlay">
                    <h3 class="card-title">{{ current_date }}</h3>
                    <p class="card-text">Date today</p>
                </div>
            </div>
        </div>
        <div class="container-fluid my-2 d-flex flex-column align-items-center">
            <div class="card container-fluid p-0 bg-dark text-white">
                <div class="card-img" style="background-image: url('{{ url_for('static', filename='images/sample.jpg') }}');"></div>
                <div class="card-img-overlay">
                    <h3 class="card-title">{{ request_count }}</h3>
                    <p class="card-text">Total requests</p>
                </div>
            </div>
        </div>
        <div class="container-fluid my-2 d-flex flex-column align-items-center">
            <div class="card container-fluid p-0 bg-dark text-white">
                <div class="card-img" style="background-image: url('{{ url_for('static', filename='images/sample.jpg') }}');"></div>
                <div class="card-img-overlay">
                    <h3 class="card-title">{{ technician_count }}</h3>
                    <p class="card-text">Total technicians</p>
                </div>
            </div>
        </div>
    </div>
    <div class="db-cc-cs position-relative row no-gutters">
        <div class="col-8">
            <div class="cs-pst card bg-light mt-2 box-shadow">
                <div class="card-body">
                    <div class="card-title mt-3 mx-3 d-flex align-items-center justify-content-between">
                        <h5 class="font-weight-bold">
                            Performed services over the months
                        </h5>
                        <div class="dropdown mb-2">
                            <a class="btn btn-outline-secondary btn-sm dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                              <a class="dropdown-item"></a>
                            </div>
                        </div>
                    </div>
                    <div class="cs-dvd"></div>
                    <div class="cs-pst-d ct-chart ct-minor-seventh d-flex justify-content-center align-items-center"></div>
                </div>
            </div>
            <div class="cs-sro card bg-light mt-2 box-shadow">
                <div class="card-body">
                    <div class="card-title mt-3 mx-3 d-flex align-items-center justify-content-between">
                        <h5 class="font-weight-bold">
                            Service requests per office
                        </h5>
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <button type="button" class="btn btn-outline-secondary btn-sm" disabled>&laquo; Highest</button>
                            <button type="button" class="btn btn-outline-secondary btn-sm" disabled>Lowest &raquo;</button>
                        </div>
                    </div>
                    <div class="cs-dvd"></div>
                    <div class="cs-sro-d ct-chart ct-octave"></div>
                    <div class="cs-sro-l container-fluid d-flex justify-content-center px-4"></div>
                </div>
            </div>
            <div class="cs-tsp card bg-light mt-2 box-shadow">
                <div class="card-body">
                    <div class="card-title mt-3 mx-3 d-flex align-items-center justify-content-between">
                        <h5 class="font-weight-bold">
                            Technicians and the services they have performed
                        </h5>
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <button type="button" class="btn btn-outline-secondary btn-sm" disabled>&laquo; Highest</button>
                            <button type="button" class="btn btn-outline-secondary btn-sm" disabled>Lowest &raquo;</button>
                        </div>
                    </div>
                    <div class="cs-dvd"></div>
                    <div class="cs-tsp-d ct-chart ct-octave"></div>
                    <div class="cs-tsp-l container-fluid d-flex justify-content-center px-4"></div>
                </div>
            </div>
        </div>
        <div class="col d-flex flex-column">
            <div class="cs-rs card ml-2 mt-2 bg-light box-shadow">
                <div class="card-body">
                    <h5 class="card-title mt-3 ml-3 ml-5 font-weight-bold">Rating summary</h5>
                    <div class="cs-dvd"></div>
                    <div class="cs-rs-d ct-chart ct-perfect-fourth"></div>
                </div>
            </div>
            {#<div class="cs-mrsn card ml-2 mt-2 bg-light box-shadow">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">Most requested service nature</h5>
                    <p class="card-text">
                        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt delectus tempore, iste error eveniet rerum deleniti doloremque voluptate nostrum illum sequi sit cumque eaque quaerat quibusdam at excepturi optio explicabo ex assumenda omnis eum officia enim laboriosam! Quam a omnis ab dolorem quaerat veritatis, in doloremque eius rem pariatur iste illo dicta autem. Eum accusamus qui nam maxime est error dolorem dignissimos incidunt, ad sit fugiat odio sed dicta modi, dolore id unde nobis atque facere sequi corrupti sunt neque! Repudiandae reiciendis omnis expedita, quos ducimus tempora ipsum natus. Culpa dolorem minima corrupti quod possimus est corporis voluptate quam aperiam!
                    </p>
                </div>
            </div>#}
        </div>
    </div>
{% endblock content %}

app/client/templates/layout.html
{% from "components.html" import sidebar %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/chartist/dist/chartist.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
        <title>ICTC | {{ page_title }}</title>
    </head>
    <body>
        <div id="ictc-st-mf" class="container-fluid mb-3">
            <div class="row d-flex justify-content-center">
                <div class="mf-sb col-2 p-0">
                    {{ sidebar(page_title) }}
                </div>
                <div class="mf-cc col-10 p-0">
                    {% block content %}{% endblock content %}
                </div>
            </div>
        </div>
        {% block fronters %}{% endblock fronters %}
        <div class="alert-frame container">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }} alert-dismissible fade show small" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
        <script src="{{ url_for('static', filename='node_modules/chartist/dist/chartist.min.js') }}"></script>
        <script src="{{ url_for('static', filename='node_modules/chartist/dist/chartist-plugin-legend.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
        <script src="{{ url_for('static', filename='node_modules/popper.js/dist/umd/popper.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    </body>
</html>